### PR TITLE
add net.py to examples

### PR DESCRIPTION
**Pull request by NtAlexio2**
Add new `net.py` file to examples as a replacement for windows `net.exe` builtin tool. Main features of this `net.py`:

- Enumerate all objects in domain/local context, **remotly** (it is not possible to remote enumeration, local object, using windows builtin `net.exe` utility)
- Read user/computer account information through **SAMR**
- Change **group membership** of accounts
- Create new user/computer accounts without touching LDAP (use RPCoverSMB instead)

### CODE REVIEW

**Comment by anadrianmanrique** [comment]
Hi! thanks for the PR and new example! I'm currently testing it. So far it's working great. A couple of comments to share:

- copyright notice should be updated in the script header
- help for subcommands it's not being shown, unless I'm missing something, executing python net.py user --help doesn't show specific help for that subcommand ( same for the others one )

**Comment by NtAlexio2** [comment]
Thanks for review @anadrianmanrique
```
usage: net.py [-h] [-debug] [-hashes LMHASH:NTHASH] [-no-pass] [-k]
               [-aesKey hex key] [-dc-ip ip address] [-target-ip ip address]
               [-port [destination port]]
               target {user,computer,localgroup,group} ...
```
According to help message, `target` is required and comes **before** entry (user/computer/etc). To get command-specific help message, you need to specify both of them. for example:
```
┌──(kali㉿kali)-[~/git/impacket/examples]
└─$ python net.py admin:1234@192.168.1.1 user --help
Impacket v0.10.1.dev1+20230411.194738.4d45b435 - Copyright 2022 Fortra

usage: net.py target user [-h] [-name NAME] [-create NAME] [-remove NAME] [-newPasswd PASSWORD]

options:
  -h, --help           show this help message and exit
  -name NAME           Display single user information.
  -create NAME         Add new user account to domain/computer.
  -remove NAME         Remove existing user account from domain/computer.
  -newPasswd PASSWORD  New password to set for creating account.
```
which `admin:1234@192.168.1.1` is target and `user` is the entry.
Is there any preferred/standard form for Impacket?

**Comment by anadrianmanrique** [comment]
Ok, I see other remote examples with subgroups parameters behave the same ( which is kind of 'weird' ).
Anyway I'm merging this, thank you!

**Comment by anadrianmanrique** [comment]
@T3KX please, could you open an issue describing steps and scenario configuration to reproduce it? I just tried adding a local user ( not though socks proxy ) and it worked fine. Thanks

**Pull request merged**
