### PR TITLE
add filter option to ntlmrelayx.py

### PR DESCRIPTION
**Pull request by shoxxdj**
Ntlmrelay is a cool tool for pentesting. 
However, when you have multiple relays it could be boring to find the one you need. 

First, I wanted to filter only the "Admin eq True" ones but I decided to allow the filter of target / username / admin status. 

Enjoy :)

### CODE REVIEW

**Comment by shoxxdj** [comment]
Hey any news ?

**Comment by anadrianmanrique** [comment]
Hi, thank you for the PR. It would be nice to have some documentation regarding the new parameters for the **_socks_** command. In that way the operator will be able to understand the command syntax for filters. That could be printed out when doing **_help socks_** in the socks CLI.

**Comment by shoxxdj** [comment]
> Hi, thank you for the PR. It would be nice to have some documentation regarding the new parameters for the **_socks_** command. In that way the operator will be able to understand the command syntax for filters. That could be printed out when doing **_help socks_** in the socks CLI.

Nice idea ! I have updated the function's docstring :)

**Comment by anadrianmanrique** [comment]
Thank you!

**Pull request merged**
