### PR TITLE
[enhancement] Adding column to show if SPN exists in finddelegations.py

### PR DESCRIPTION
**Pull request by p0dalirius**
Hi,

I have added a new column "SPN Exists" to easily see if SPN Jacking is possible.

Here is a redacted example of output:
image

Best regards,

### CODE REVIEW

**Comment by gabrielg5** [comment]
Hi @p0dalirius,

Checking your changes I found a path that is triggering an error when generating the output.

This line is not setting any value to the new column
https://github.com/fortra/impacket/blob/269ce69872f0e8f2188a80addb0c39fedfa6dcb8/examples/findDelegation.py#L228

which is resulting in an exception iterating rows to draw the table
https://github.com/fortra/impacket/blob/269ce69872f0e8f2188a80addb0c39fedfa6dcb8/examples/findDelegation.py#L40-L44

Also, could you revert those quoting changes? that makes the PR more atomic and helps validate what is the real change

thank you!!

**Comment by p0dalirius** [comment]
Hi @gabrielg5,

I have fixed the code path

I have reverted the quoting changes, although the code really should be double quoted and not single quoted everywhere.  

Best regards,

**Comment by gabrielg5** [comment]
Hey @p0dalirius,

great! just one last ask before merging this PR... Can you extract the `spnExists` resolution to an external function to avoid duplicating those lines?

thank you!

**Comment by p0dalirius** [comment]
Done :)

**Comment by gabrielg5** [comment]
Merging now..
Thank you!

**Pull request merged**
