### PR TITLE
Incorporate Pennyw0rth/NetExec Impacket changes into Fortra Impacket (reloaded)

### PR DESCRIPTION
**Pull request by mpgn**
Fixing all the issues with PR https://github.com/fortra/impacket/pull/1715

> NetExec is attempting to get added to Kali Linux as a default package, but we currently have several changes in our Impacket fork that are required to be merged into upstream.

> The GKDI stuff has been used for almost a year now with no problems, and @XiaoliChan recently had some other changes merged related to NetExec changes. I just filed https://github.com/fortra/impacket/pull/1714 as well to revert some breaking changes that we require.

> This is necessary because we do not want to have another impacket Kali package deployed, as that causes confusion, and we're not even sure if Kali would want that. The easiest way is to have our changes merged into upstream.

> Please let me know if there are any issues testing these changes.

### CODE REVIEW

**Comment by NeffIsBack** [comment]
Cleanly cherry-picked the commits that matter, nice work👌🏼
If these are merged we should be ready to go for kali packaging.

**Comment by Marshall-Hallenbeck** [comment]
@mpgn can you remove f90196bad354b18bec4e6e04dfa3f823df9e74aa from this PR? @XiaoliChan and I spoke and we think it should be removed since it's hardcoding a timeout and using a global variable. He has let me know it won't break anything (we can test, of course).

**Comment by mpgn** [comment]
We can't, `set_connect_timeout` is used a lot on nxc with a custom timeout, example: https://github.com/Pennyw0rth/NetExec/blob/main/nxc/connection.py#L71

**Comment by XiaoliChan** [comment]
> `set_connect_timeout` is used a lot on nxc with a custom timeout, example: https://github.com/Pennyw0rth/NetExec/blob/main/nxc/connection.py#L71
> 
> Removing the commit will break nxc from what I see

Oh, that is rpctransport, the `set_connect_timeout` I added is like dcom.set_connect_timeout not rpctransport

**Comment by mpgn** [comment]
Should be good @Marshall-Hallenbeck :)

**Comment by anadrianmanrique** [comment]
Hello, I'll  be reviewing/testing this PR changes.
Some comments/questions:
- srvs.py / smbconnection.py a.k.a #947 : do you guys have any idea how to reproduce the issue these changes are actually fixing?
- ntlm.py : following this up in #1626. These changes are not going to be merged

**Comment by mpgn** [comment]
Hello @anadrianmanrique if you fix the problem of LM computing hash in another PR, i will remove the commit on this PR 😉

**Comment by Marshall-Hallenbeck** [comment]
> * srvs.py / smbconnection.py a.k.a [Add ServerName argument to srvs.hNetrShareEnum #947](https://github.com/fortra/impacket/pull/947) : do you guys have any idea how to reproduce the issue these changes are actually fixing?

So from my understanding of the spec, impacket defaults to NULL, which is just the localhost, but we need to define a DNS/NetBios name per: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-srvs/5f8329ee-1965-4ea1-ad35-3b29fbb63232

I'm surprised this hasn't caused more issues, actually, since I would think it would only allow connecting to the localhost.

**Comment by Marshall-Hallenbeck** [comment]
Hmm yeah sorry I don't have a specific retestable scenario. @NeffIsBack did you?

**Comment by anadrianmanrique** [comment]
> Hello @anadrianmanrique if you fix the problem of LM computing hash in another PR, i will remove the commit on this PR 😉

wether the problem gets fixed or not, this PR will not be approved/merged, as long as it contains changes from #1626, so please remove that commit. In this moment #1723 it's being tested and problably merged today/tomorrow ;)

**Comment by mpgn** [comment]
> > Hello @anadrianmanrique if you fix the problem of LM computing hash in another PR, i will remove the commit on this PR 😉
> 
> wether the problem gets fixed or not, this PR will not be approved/merged, as long as it contains changes from #1626, so please remove that commit. In this moment #1723 it's being tested and problably merged today/tomorrow ;)

I will do it tonight 👍

**Comment by mpgn** [comment]
done @anadrianmanrique :)

**Comment by anadrianmanrique** [comment]
sorry, I forgot, changes in srvs.py and smbconnection.py should be removed also from this PR. I've just merged the original PR containing these changes.

**Comment by anadrianmanrique** [comment]
Ok, thanks, PR is ready to merge then!

**Comment by anadrianmanrique** [comment]
Merged changes from #947 here, as the original PR needs to be rebased.

**Comment by anadrianmanrique** [comment]
Thank you guys! Let us now in comments if you find in the future PRs that you'll need integrated, in order to allow us to improve our prioritization.

**Comment by mpgn** [comment]
Thank you @anadrianmanrique !

**Comment by anadrianmanrique** [comment]
FYI #1723 was merged as well

**Pull request merged**
