### PR TITLE
Add ldapshell dirsync/whoami

### PR DESCRIPTION
**Pull request by nurfed1**
Add support dirsync (https://simondotsh.com/infosec/2022/07/11/dirsync.html) and whoami in ldap shell

### CODE REVIEW

**Comment by blacklist-arcc** [comment]
any example usage of the command? want to check out this new feature in a live environment and not shure abount the correct parameters

**Comment by blacklist-arcc** [comment]
Thanks for this nice feature - waiting for the merge =)
have already published an article about this: https://evait.medium.com/ntlm-relay-vs-laps-e2602331701e

**Comment by mpgn** [comment]
@blacklist-arcc the concept of this attack with ntlmrelayx is dependant of NTLMv1 which need to be enabled on the DC not just NTLM as you describe on the article because of the `remove-mic` flag. This is a huge difference and if you have ntlmv1 you can just get the hash and crack it with crack.sh :)

**Comment by blacklist-arcc** [comment]
I was not shure about the ntlmv1 because we could not test with ntlmv2 in this scenario - but good point, i will modify the article. Btw. crack.sh service is down for quite a while. We are considering to generate a rainbowtable for 112233...challanges for ourselves. Thanks for make this clearer to me!

**Comment by mpgn** [comment]
Yep :) 

> relaying SMB to LDAP is not possible, because SMB sets a flag which requires messages to be signed with a session key

https://www.trustedsec.com/blog/practical-attacks-against-ntlmv1/

**Comment by mpgn** [comment]
> We are considering to generate a rainbowtable for 112233...challanges for ourselves. 

that would be awesome to test if this is faisable yes

**Comment by blacklist-arcc** [comment]
> > We are considering to generate a rainbowtable for 112233...challanges for ourselves.
> 
> that would be awesome to test if this is faisable yes

We found nothing on the internet that can be downloaded for this challange and the whole DES keyspace. Thanks for your help on this topic!

**Pull request merged**
