### PR TITLE
The tree command of "smbclient.py" does not parse the path correct.

### PR DESCRIPTION
**Pull request by trietend**
The tree command of "smbclient.py" does not parse the path correct.

Reproduce bug:

Server Side:
```
mkdir /tmp/smb /tmp/smb/test/ /tmp/smb/test/folder; touch /tmp/smb/test/file /tmp/smb/test/folder/file

tree /tmp/smb
/tmp/smb
└── test
    ├── file
    └── folder
        └── file

sudo smbserver.py share /tmp/smb
```

Client Side:
```
Impacket v0.12.0.dev1+20230907.33311.3f645107 - Copyright 2023 Fortra

Type help for list of commands
# use share
# tree
//test/folder
//test/file
Finished - 3 files and folders
# tree .
[-] SMB SessionError: STATUS_OBJECT_PATH_SYNTAX_BAD(The object path component was not a directory object.)
# cd test
# tree
/test//file
/test/folder/file
Finished - 2 files and folders
# tree /
[-] SMB SessionError: STATUS_OBJECT_PATH_SYNTAX_BAD(The object path component was not a directory object.)
```

### CODE REVIEW

**Comment by gabrielg5** [comment]
Hi @trietend!

Thank for this PR!. I've been checking a bit your changes and tested with many different path configurations, all worked fine except for one that is tearing down the connection.

If I run `tree <non-existent-folder>` the pipe is broken and I need to set up a new connection.
Current `master` code is keeping the connection open

### Testing with `master`
**Server**
```
┌──(xxxx㉿XXXXXX)-[~/Desktop/impacket/examples]
└─$ python smbserver.py share /tmp/smb
Impacket v0.12.0.dev1+20230921.20754.9c8f344b - Copyright 2023 Fortra

[*] Config file parsed
[*] Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
[*] Callback added for UUID 6BFFD098-A112-3610-9833-46C3F87E345A V:1.0
[*] Config file parsed
[*] Config file parsed
[*] Config file parsed
[*] Incoming connection (xxx.XXX.xxx.XXX,36360)
[*] AUTHENTICATE_MESSAGE (\,)
[*] User \ authenticated successfully
[*] :::00::aaaaaaaaaaaaaaaa
[*] Disconnecting Share(2:SHARE)
[-] Path not in current working directory
[*] Disconnecting Share(2:SHARE)
```

**Client**
```
┌──(xxxx㉿XXXXXX)-[~/Desktop/impacket/examples]
└─$ python smbclient.py xxx.XXX.xxx.XXX
Impacket v0.12.0.dev1+20230921.20754.9c8f344b - Copyright 2023 Fortra

Type help for list of commands
# use share
# tree saraza
//saraza/*
[-] SMB SessionError: STATUS_OBJECT_PATH_SYNTAX_BAD(The object path component was not a directory object.)
#
```

### Testing with `pr`
**Server**
```
┌──(xxxx㉿XXXXXX)-[~/Desktop/impacket/examples]
└─$ python smbserver.py share /tmp/smb
Impacket v0.12.0.dev1+20230914.154425.a18119c2 - Copyright 2023 Fortra

[*] Config file parsed
[*] Callback added for UUID 4B324FC8-1670-01D3-1278-5A47BF6EE188 V:3.0
[*] Callback added for UUID 6BFFD098-A112-3610-9833-46C3F87E345A V:1.0
[*] Config file parsed
[*] Config file parsed
[*] Config file parsed
[*] Incoming connection (xxx.XXX.xxx.XXX,57676)
[*] AUTHENTICATE_MESSAGE (\,)
[*] User \ authenticated successfully
[*] :::00::aaaaaaaaaaaaaaaa
[*] Disconnecting Share(2:SHARE)
[-] Transaction2: (0x1,[Errno 2] No such file or directory: '/tmp/smb/saraza')
[-] processRequest (0x32,[Errno 2] No such file or directory: '/tmp/smb/saraza')
[*] Handle: [Errno 2] No such file or directory: '/tmp/smb/saraza'
```

**Client**
```
┌──(xxxx㉿XXXXXX)-[~/Desktop/impacket/examples]
└─$ python smbclient.py xxx.XXX.xxx.XXX
Impacket v0.12.0.dev1+20230914.154425.a18119c2 - Copyright 2023 Fortra

Type help for list of commands
# use share
# tree saraza
/saraza/*
[-] Error while reading from remote
#
```

**Comment by trietend** [comment]
Hi @gabrielg5,
i am not really sure why it worked before :)

For me it looks like it is a bug in smbserver.py is closing the connection.

```
[-] Transaction2: (0x1,[Errno 2] No such file or directory: '/tmp/smb/test/aaa')
[-] processRequest (0x32,[Errno 2] No such file or directory: '/tmp/smb/test/aaa')
[*] Handle: [Errno 2] No such file or directory: '/tmp/smb/test/aaa'
[*] Closing down connection (127.0.0.1,45460)
[*] Remaining connections []
```

The same happens if you `cd` into a file

```
# cd file 
# ls
[-] Error while reading from remote
```


For me it feels like this shouldn't be fixed here.

Testing it against a windows SMB server I also get:

```
[-] SMB SessionError: STATUS_OBJECT_NAME_NOT_FOUND(The object name is not found.)
```

**Comment by gabrielg5** [comment]
yeah, I guess the smbserver may not be handling properly the _"new"_ paths.

in the master version non-existent path is `//folder/*`; while in the PR one, it is `/folder/*`

the issue should be coming from there... will take a look at it

**Comment by trietend** [comment]
The stacktrace for a non-existing folder was.

```
[*] Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/impacket/smbserver.py", line 3943, in handle
    resp = self.__SMB.processRequest(self.__connId, p.get_trailer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/impacket/smbserver.py", line 4417, in processRequest
    respCommands, respPackets, errorCode = self.__smbCommands[packet['Command']](
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/impacket/smbserver.py", line 1361, in smbTransaction2
    setup, parameters, data, errorCode = transCommands[command](connId,
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/impacket/smbserver.py", line 984, in findFirst2
    searchResult, searchCount, errorCode = findFirst2(path,
                                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/impacket/smbserver.py", line 417, in findFirst2
    for file in os.listdir(dirName):
                ^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/tmp/smb/nonexisting'
```

I added a check in smbserver, if the path exists before listing it.

**Comment by gabrielg5** [comment]
Thank you @trietend! :tada:

**Pull request merged**
